server:
  port: 9099
spring:
  application:
    name: Transaction-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true